name: 🐞 Bug
description: Create a bug report to help us to improve the libary.
title: "[BUG]:"
labels: ["bug"]
body:
  - type: textarea
    id: current-behaivor
    attributes:
      label: What's the current behavior?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behaivor
    attributes:
      label: Expected Behaivor?
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what is the expected behaivor!
      value: "The bug shouldn't be exists!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **simple-amari.py**: 1.0.1
          - **pip / python**: 3.9
      value: |
          - pip / python:
          - simple-amari.py:
      render: markdown
      validations:
        required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/InvalidLenni/simple-amari.py#code_of_conduct.md)
          required: true
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
