blank_issues_enabled: false
contact_links:
  - name: simple-amari.py Discord Server
    url: https://discord.gg/GmznjF7HJf
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://invalidlenni.de/simple-amari.py/
    about: Please read the docs.
  - name: AmariBot Developer Panel
    url: https://amaribot.com/developer/
    about: The developer panel by the AmariBot.
  - name: AmariBot Support Server
    url: https://amaribot.com/support
    about: Please ask and answer questions there about the bot.
